import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:official_chatbox_application/core/constants/colors.dart';
import 'package:official_chatbox_application/core/constants/height_width.dart';
import 'package:official_chatbox_application/features/presentation/widgets/ai/ai_small_widgets.dart';
import 'package:official_chatbox_application/features/presentation/widgets/chat/icon_container_widget_gradient_color.dart';
import 'package:official_chatbox_application/features/presentation/widgets/common_widgets/divider_common.dart';
import 'package:official_chatbox_application/features/presentation/widgets/common_widgets/text_widget_common.dart';

class AIChatInfoPage extends StatelessWidget {
  const AIChatInfoPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: GestureDetector(
          onTap: () {
            Navigator.pop(context);
          },
          child: Icon(
            Icons.arrow_back,
            color: Theme.of(context).colorScheme.onPrimary,
          ),
        ),
        title: boxAITitle(),
      ),
      body: SizedBox(
        width: screenWidth(context: context),
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 18.w),
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                kHeight10,
                imageContainer(size: 140),
                kHeight5,
                boxAITitle(fontSize: 30.sp),
                kHeight10,
                iconContainerWidgetGradientColor(
                  size: 78,
                  subtitle: "Chat",
                  icon: Icons.chat_outlined,
                  onTap: () {
                    Navigator.pop(context);
                  },
                ),
                CommonDivider(
                  thickness: 5,
                  color: iconGreyColor.withOpacity(0.2),
                ),
                kHeight15,
                Container(
                  padding:
                      EdgeInsets.symmetric(horizontal: 10.w, vertical: 10.h),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10.sp),
                    color: iconGreyColor.withOpacity(0.3),
                  ),
                  child: TextWidgetCommon(
                    text:
                        "Messages are generated by AI. Some may be inaccurate or inappropriate.",
                    fontSize: 16.sp,
                    fontWeight: FontWeight.normal,
                    textAlign: TextAlign.center,
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
